In [1]:
#import necessary libraries
import pandas as pd
import numpy as np

In [12]:
#fetch the file
test2 = pd.read_csv ('energydata_complete (1).csv')
test = test2.set_index('date')

In [13]:
test.head(2)

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
date,,,,,,,,,,,,,,,,,,,,,
2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.7900,19.79,44.73,19.0,45.566667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.7225,19.79,44.79,19.0,45.992500,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195

In [14]:
#Firstly, we normalise our dataset to a common scale using the min max scaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
normalised_test =  pd.DataFrame(scaler.fit_transform(test), columns=test.columns)
features_test = normalised_test.drop(columns=[ 'lights' ])
target = normalised_test['Appliances']

In [15]:
features_test.head(2)

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.50000,0.953846,0.538462,0.265449,0.265449
1,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.47619,0.894872,0.533937,0.372083,0.372083

In [16]:
#Now, we split our dataset into the training and testing dataset. Recall that we had earlier segmented the features and target variables.

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_test, target, test_size= 0.3 , random_state= 42 )

In [17]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()
#model = LinearRegression()
#fit the model to the training dataset

linear_model.fit(x_train, y_train)
#model.fit(x_train, y_train)

LinearRegression()

In [18]:
#obtain predictions

predicted_values = linear_model.predict(x_test)

In [19]:
#MAE

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 3 )

0.05

In [20]:
# _Residual Sum of Squares (RSS)_



rss = np.sum(np.square(y_test - predicted_values))
round(rss, 3 )

45.348

In [21]:
# _Root Mean Square Error (RMSE)_

from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3 )

0.088

In [22]:
# _R-Squared_

from sklearn.metrics import r2_score

r2_score = r2_score(y_test, predicted_values)
round(r2_score, 3 )

0.149

In [23]:
#_Ridge Regression_

from sklearn.linear_model import Ridge

ridge_reg = Ridge(alpha= 0.4 )
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.4)

In [29]:

from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3 )

0.088

In [24]:
#_Feature Selection and Lasso Regression_

from sklearn.linear_model import Lasso

lasso_reg = Lasso(alpha= 0.001 )
lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.001)

In [30]:

from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3 )

0.088

In [25]:
#comparing the effects of regularisation

def get_weights_test(model, feat, col_name):
#this function returns the weight of every feature (the following codes should be in an indented block)
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_test = pd.DataFrame(weights).reset_index()
    weights_test.columns = [ 'Features' , col_name]
    weights_test[col_name].round(3)
    return weights_test
    return weights_test

In [26]:
linear_model_weights = get_weights_test(linear_model, x_train, 'Linear_Model_Weight' )
ridge_weights_test = get_weights_test(ridge_reg, x_train, 'Ridge_Weight' )
lasso_weights_test = get_weights_test(lasso_reg, x_train, 'Lasso_weight' )

In [27]:
lasso_weights_test

       Features  Lasso_weight
0        RH_out     -0.049557
1          RH_8     -0.000110
2            T1      0.000000
3     Tdewpoint      0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      0.002912
25         RH_1      0.017880

In [28]:
final_weights = pd.merge(linear_model_weights, ridge_weights_test, on= 'Features' )
final_weights = pd.merge(final_weights, lasso_weights_test, on= 'Features' )

final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.411071     -0.000000
1         T_out            -0.321860     -0.262172      0.000000
2            T2            -0.236178     -0.201397      0.000000
3            T9            -0.189941     -0.188916     -0.000000
4          RH_8            -0.157595     -0.156830     -0.000110
5        RH_out            -0.077671     -0.054724     -0.049557
6          RH_7            -0.044614     -0.045977     -0.000000
7          RH_9            -0.039800     -0.041367     -0.000000
8            T5            -0.015657     -0.019853     -0.000000
9            T1            -0.003281     -0.018406      0.000000
10          rv1             0.000770      0.000748     -0.000000
11          rv2             0.000770      0.000748     -0.000000
12  Press_mm_hg             0.006839      0.006584     -0.000000
13           T7             0.010319      0.010098     -0.000000
14   Visibility             0.012307      0.012076      0.000000
15         RH_5             0.016006      0.016152      0.000000
16         RH_4             0.026386      0.024579      0.000000
17           T4             0.028981      0.027384     -0.000000
18    Windspeed             0.029183      0.030268      0.002912
19         RH_6             0.038049      0.035519     -0.000000
20         RH_3             0.096048      0.095135      0.000000
21           T8             0.101995      0.101028      0.000000
22    Tdewpoint             0.117758      0.083128      0.000000
23           T6             0.236425      0.217292      0.000000
24           T3             0.290627      0.288087      0.000000
25         RH_1             0.553547      0.519525      0.017880